/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imatapp_g8;

import javax.swing.JLabel;
import se.chalmers.ait.dat215.project.ProductCategory;

/**
 *
 * @author frellAn
 */
public class Breadcrumbs extends javax.swing.JPanel {

    Controller controller;
    
    /**
     * Creates new form Breadcrumbs
     */
    public Breadcrumbs() {
        initComponents();
        controller = Controller.getInstance();
    }
    
    public void updateLabels(String one, String two, String three) {
        // Update FIRST set
        if (one == null) {
            first.setText("");
        } else {
            first.setText(" " + one);
        }
        // Update SECOND set
        if (two == null) {
            arrow1.setText("");
            second.setText("");
        } else if (!two.equals("KEEP")) {
            arrow1.setText(">");
            second.setText(two);
        } else {}
        // Update THIRD set
        if (three == null) {
            arrow2.setText("");
            third.setText("");
        } else {
            arrow2.setText(">");
            third.setText(three);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        first = new javax.swing.JLabel();
        arrow1 = new javax.swing.JLabel();
        second = new javax.swing.JLabel();
        arrow2 = new javax.swing.JLabel();
        third = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(930, 32767));
        setMinimumSize(new java.awt.Dimension(930, 0));
        setPreferredSize(new java.awt.Dimension(930, 30));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        first.setFont(new java.awt.Font("Myriad Pro", 0, 19)); // NOI18N
        first.setText("first");
        first.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        first.setMaximumSize(new java.awt.Dimension(100, 20));
        first.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstMouseClicked(evt);
            }
        });
        add(first);

        arrow1.setFont(new java.awt.Font("Myriad Pro", 1, 19)); // NOI18N
        arrow1.setText(">");
        add(arrow1);

        second.setFont(new java.awt.Font("Myriad Pro", 0, 19)); // NOI18N
        second.setText("second");
        second.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        second.setMaximumSize(new java.awt.Dimension(200, 20));
        second.setMinimumSize(new java.awt.Dimension(90, 20));
        second.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondMouseClicked(evt);
            }
        });
        add(second);

        arrow2.setFont(new java.awt.Font("Myriad Pro", 1, 19)); // NOI18N
        arrow2.setText(">");
        add(arrow2);

        third.setFont(new java.awt.Font("Myriad Pro", 0, 19)); // NOI18N
        third.setText("third");
        third.setMaximumSize(new java.awt.Dimension(200, 20));
        add(third);
    }// </editor-fold>//GEN-END:initComponents

    private void secondMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondMouseClicked
        controller.updateBreadcrumbs("Butik","KEEP",null);
        controller.showPreviousShopCategory();
    }//GEN-LAST:event_secondMouseClicked

    private void firstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstMouseClicked
        // null
    }//GEN-LAST:event_firstMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrow1;
    private javax.swing.JLabel arrow2;
    private javax.swing.JLabel first;
    private javax.swing.JLabel second;
    private javax.swing.JLabel third;
    // End of variables declaration//GEN-END:variables
}
