/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imatapp_g8;

import java.util.ArrayList;
import java.util.List;
import se.chalmers.ait.dat215.project.*;

/**
 *
 * @author frellAn
 */
public class CartPanel extends javax.swing.JPanel {
    
    // Custom variable declaration
    static Controller controller;
    private static double totalPrice;
    
    /**
     * Creates new form ShopPanel
     */
    public CartPanel() {
        controller = Controller.getInstance();
        totalPrice = (Math.round(controller.cart.getTotal()*100.0)/100.0) + controller.getShippingPrice();
        initComponents();
        List<ShoppingItem> tempList;
        tempList = Controller.cart.getItems();
        for (ShoppingItem item : tempList) {
            itemsGrid.add(new CartPanelItem(item));
        }
    }
    
    public static void update() {
        itemsGrid.removeAll();
        itemsGrid.repaint();
        for (int i = 0; i < Controller.cart.getItems().size(); i++) {
            itemsGrid.add(new CartPanelItem(Controller.cart.getItems().get(i)));
        }
        itemsGrid.revalidate();
        totalPrice = (Math.round(controller.cart.getTotal()*100.0)/100.0) + controller.getShippingPrice();
        productsPriceLabel.setText("Produktkostnad: " + Double.toString((Math.round(controller.cart.getTotal()*100.0)/100.0)) + " kr");
        productsTaxPriceLabel.setText("Varav moms: " + Double.toString((Math.round(controller.cart.getTotal()*12.0)/100.0)) + " kr");
        totalPriceLabel.setText("Totalsumma: " + Double.toString(totalPrice) + " kr");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        itemGridScrollPane = new javax.swing.JScrollPane();
        itemsGrid = new javax.swing.JPanel();
        checkoutBtn = new javax.swing.JButton();
        shippingPriceLabel = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        headerLabel = new javax.swing.JLabel();
        shippingHeaderLabel = new javax.swing.JLabel();
        shippingOptionsPanel = new javax.swing.JPanel();
        shippingOption1Button = new javax.swing.JRadioButton();
        shippingOption2Button = new javax.swing.JRadioButton();
        shippingOption3Button = new javax.swing.JRadioButton();
        productsPriceLabel = new javax.swing.JLabel();
        productsTaxPriceLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(930, 32767));
        setMinimumSize(new java.awt.Dimension(930, 630));
        setPreferredSize(new java.awt.Dimension(930, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemGridScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        itemGridScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        itemsGrid.setBackground(new java.awt.Color(255, 255, 255));
        itemsGrid.setAlignmentX(0.0F);
        itemsGrid.setAlignmentY(0.0F);
        itemsGrid.setMaximumSize(new java.awt.Dimension(920, 590));
        itemsGrid.setLayout(new java.awt.GridLayout(0, 1));
        itemGridScrollPane.setViewportView(itemsGrid);

        add(itemGridScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 44, 660, 570));

        checkoutBtn.setFont(new java.awt.Font("Myriad Pro Light", 0, 17)); // NOI18N
        checkoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green_icon.png"))); // NOI18N
        checkoutBtn.setText("Köp");
        checkoutBtn.setAlignmentY(0.0F);
        checkoutBtn.setBorder(null);
        checkoutBtn.setBorderPainted(false);
        checkoutBtn.setContentAreaFilled(false);
        checkoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkoutBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        checkoutBtn.setDefaultCapable(false);
        checkoutBtn.setFocusPainted(false);
        checkoutBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        checkoutBtn.setIconTextGap(0);
        checkoutBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkoutBtn.setMaximumSize(new java.awt.Dimension(110, 46));
        checkoutBtn.setMinimumSize(new java.awt.Dimension(110, 46));
        checkoutBtn.setPreferredSize(new java.awt.Dimension(110, 46));
        checkoutBtn.setRequestFocusEnabled(false);
        checkoutBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/green_icon_rollover.png"))); // NOI18N
        checkoutBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/green_icon_selected.png"))); // NOI18N
        checkoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBtnActionPerformed(evt);
            }
        });
        add(checkoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 580, 118, 36));

        shippingPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        shippingPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        shippingPriceLabel.setText("Fraktkostnad: " + Double.toString(controller.getShippingPrice()) + " kr"
        );
        add(shippingPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 515, 180, -1));

        totalPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        totalPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalPriceLabel.setText("Totalsumma: " + Double.toString((Math.round(controller.cart.getTotal()*100.0)/100.0) + controller.getShippingPrice()) + " kr"
        );
        add(totalPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 240, -1));

        headerLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        headerLabel.setText("Välj fraktsätt:");
        add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 14, -1, -1));

        shippingHeaderLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        shippingHeaderLabel.setText("Produkter i kundvagnen:");
        add(shippingHeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 14, -1, -1));

        shippingOptionsPanel.setBackground(new java.awt.Color(255, 255, 255));
        shippingOptionsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        shippingOptionsPanel.setLayout(new java.awt.GridLayout(3, 1));

        shippingOption1Button.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(shippingOption1Button);
        shippingOption1Button.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        shippingOption1Button.setAlignmentY(0.0F);
        shippingOption1Button.setBorder(null);
        shippingOption1Button.setContentAreaFilled(false);
        shippingOption1Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shippingOption1Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shipping1_icon.png"))); // NOI18N
        shippingOption1Button.setIconTextGap(0);
        shippingOption1Button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        shippingOption1Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/shipping1_icon_rollover.png"))); // NOI18N
        shippingOption1Button.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/shipping1_icon_selected.png"))); // NOI18N
        shippingOption1Button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        shippingOption1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shippingOption1ButtonActionPerformed(evt);
            }
        });
        shippingOptionsPanel.add(shippingOption1Button);

        shippingOption2Button.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(shippingOption2Button);
        shippingOption2Button.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        shippingOption2Button.setAlignmentY(0.0F);
        shippingOption2Button.setBorder(null);
        shippingOption2Button.setContentAreaFilled(false);
        shippingOption2Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shippingOption2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shipping2_icon.png"))); // NOI18N
        shippingOption2Button.setIconTextGap(0);
        shippingOption2Button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        shippingOption2Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/shipping2_icon_rollover.png"))); // NOI18N
        shippingOption2Button.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/shipping2_icon_selected.png"))); // NOI18N
        shippingOption2Button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        shippingOption2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shippingOption2ButtonActionPerformed(evt);
            }
        });
        shippingOptionsPanel.add(shippingOption2Button);

        shippingOption3Button.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(shippingOption3Button);
        shippingOption3Button.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        shippingOption3Button.setAlignmentY(0.0F);
        shippingOption3Button.setBorder(null);
        shippingOption3Button.setContentAreaFilled(false);
        shippingOption3Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shippingOption3Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shipping3_icon.png"))); // NOI18N
        shippingOption3Button.setIconTextGap(0);
        shippingOption3Button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        shippingOption3Button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/shipping3_icon_rollover.png"))); // NOI18N
        shippingOption3Button.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/shipping3_icon_selected.png"))); // NOI18N
        shippingOption3Button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        shippingOption3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shippingOption3ButtonActionPerformed(evt);
            }
        });
        shippingOptionsPanel.add(shippingOption3Button);

        add(shippingOptionsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 44, 230, 398));

        productsPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        productsPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        productsPriceLabel.setText("Produktkostnad: " + Double.toString((Math.round(controller.cart.getTotal()*100.0)/100.0)) + " kr");
        add(productsPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 457, 200, -1));

        productsTaxPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        productsTaxPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        productsTaxPriceLabel.setText("Varav moms: " + Double.toString((Math.round(controller.cart.getTotal()*12.0)/100.0)) + " kr");
        add(productsTaxPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 486, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed
        controller.showBuyPanel();
    }//GEN-LAST:event_checkoutBtnActionPerformed

    private void shippingOption1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shippingOption1ButtonActionPerformed
        controller.setShippingType(1);
        shippingPriceLabel.setText("Fraktkostnad: " + Double.toString(controller.getShippingPrice()) + " kr");
        update();
    }//GEN-LAST:event_shippingOption1ButtonActionPerformed

    private void shippingOption2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shippingOption2ButtonActionPerformed
        controller.setShippingType(2);
        shippingPriceLabel.setText("Fraktkostnad: " + Double.toString(controller.getShippingPrice()) + " kr");
        update();
    }//GEN-LAST:event_shippingOption2ButtonActionPerformed

    private void shippingOption3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shippingOption3ButtonActionPerformed
        controller.setShippingType(3);
        shippingPriceLabel.setText("Fraktkostnad: " + Double.toString(controller.getShippingPrice()) + " kr");
        update();
    }//GEN-LAST:event_shippingOption3ButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JScrollPane itemGridScrollPane;
    private static javax.swing.JPanel itemsGrid;
    protected static javax.swing.JLabel productsPriceLabel;
    protected static javax.swing.JLabel productsTaxPriceLabel;
    private javax.swing.JLabel shippingHeaderLabel;
    private javax.swing.JRadioButton shippingOption1Button;
    private javax.swing.JRadioButton shippingOption2Button;
    private javax.swing.JRadioButton shippingOption3Button;
    private javax.swing.JPanel shippingOptionsPanel;
    protected static javax.swing.JLabel shippingPriceLabel;
    protected static javax.swing.JLabel totalPriceLabel;
    // End of variables declaration//GEN-END:variables
}
