/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imatapp_g8;

import se.chalmers.ait.dat215.project.*;

/**
 *
 * @author Michel
 */
public class DetailedPanel extends javax.swing.JPanel {

    private Product currentProduct;
    Controller controller;
    
    /**
     * Creates new form DetailedPanel
     */
    public DetailedPanel() {
        initComponents();
    }
    
    public DetailedPanel(Product product) {
        currentProduct = product;
        controller = Controller.getInstance();
        initComponents();
        productIcon.setIcon(Controller.db.getImageIcon(product, 300, 225));
        productTitleLabel.setText(product.getName());
        priceLabel.setText("Pris: " + product.getPrice() + " kr");
        altPriceLabel.setText("Jmf pris: " + product.getPrice() + " " + product.getUnit());
        unitLabel.setText(product.getUnitSuffix());
        if (product.getUnitSuffix().equals("förp") || product.getUnitSuffix().equals("st")) {
            spinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(1.0d), 1.0, null, Double.valueOf(1.0d)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productIcon = new javax.swing.JLabel();
        mainInfoPanel = new javax.swing.JPanel();
        infoScrollPane = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        productTitleLabel = new javax.swing.JLabel();
        infoHeaderLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buyPanel = new javax.swing.JPanel();
        spinner = new javax.swing.JSpinner();
        priceLabel = new javax.swing.JLabel();
        altPriceLabel = new javax.swing.JLabel();
        addToCartBtn = new javax.swing.JButton();
        unitLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(930, 630));
        setMinimumSize(new java.awt.Dimension(930, 630));
        setPreferredSize(new java.awt.Dimension(930, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productIcon.setBackground(java.awt.Color.orange);
        productIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        productIcon.setOpaque(true);
        add(productIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 300, 225));

        mainInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoScrollPane.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("...");
        jTextArea1.setBorder(null);
        infoScrollPane.setViewportView(jTextArea1);

        mainInfoPanel.add(infoScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 109, 509, 300));

        productTitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        productTitleLabel.setFont(new java.awt.Font("Myriad Pro Light", 0, 36)); // NOI18N
        productTitleLabel.setText("<Varunamn>");
        productTitleLabel.setOpaque(true);
        mainInfoPanel.add(productTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 293, -1));

        infoHeaderLabel.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        infoHeaderLabel.setText("Produktinformation:");
        mainInfoPanel.add(infoHeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 70, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        mainInfoPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 96, 519, 10));

        add(mainInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 45, -1, -1));

        buyPanel.setBackground(new java.awt.Color(255, 255, 255));
        buyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(1.0d), Double.valueOf(0.1d), null, Double.valueOf(0.1d)));
        spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerStateChanged(evt);
            }
        });
        buyPanel.add(spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 68, 50, 27));

        priceLabel.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        priceLabel.setText("Pris: <Pris> kr");
        buyPanel.add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        altPriceLabel.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        altPriceLabel.setText("Jmf pris: <Pris> kr/kg");
        buyPanel.add(altPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 43, -1, -1));

        addToCartBtn.setFont(new java.awt.Font("Myriad Pro Light", 0, 16)); // NOI18N
        addToCartBtn.setForeground(new java.awt.Color(255, 255, 255));
        addToCartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buy_icon.png"))); // NOI18N
        addToCartBtn.setText("Lägg till");
        addToCartBtn.setAlignmentY(0.0F);
        addToCartBtn.setBorder(null);
        addToCartBtn.setBorderPainted(false);
        addToCartBtn.setContentAreaFilled(false);
        addToCartBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addToCartBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        addToCartBtn.setDefaultCapable(false);
        addToCartBtn.setFocusPainted(false);
        addToCartBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addToCartBtn.setIconTextGap(0);
        addToCartBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        addToCartBtn.setMaximumSize(new java.awt.Dimension(110, 46));
        addToCartBtn.setMinimumSize(new java.awt.Dimension(110, 46));
        addToCartBtn.setPreferredSize(new java.awt.Dimension(110, 46));
        addToCartBtn.setRequestFocusEnabled(false);
        addToCartBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buy_icon_rollover.png"))); // NOI18N
        addToCartBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/buy_icon_selected.png"))); // NOI18N
        addToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartBtnActionPerformed(evt);
            }
        });
        buyPanel.add(addToCartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 66, 80, 32));

        unitLabel.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        unitLabel.setText("<Unit>");
        buyPanel.add(unitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 67, -1, -1));

        add(buyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 300, 110));

        jLabel14.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel14.setText("Ingår i dessa recept:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 441, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 461, 890, 10));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 833, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 477, 835, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartBtnActionPerformed
        controller.addToCart(currentProduct,(double)spinner.getValue());
    }//GEN-LAST:event_addToCartBtnActionPerformed

    private void spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerStateChanged
        priceLabel.setText("Pris: " + (Math.round(currentProduct.getPrice()*(double)spinner.getValue()*100.0)/100.0) + " kr");
    }//GEN-LAST:event_spinnerStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartBtn;
    private javax.swing.JLabel altPriceLabel;
    private javax.swing.JPanel buyPanel;
    private javax.swing.JLabel infoHeaderLabel;
    private javax.swing.JScrollPane infoScrollPane;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel mainInfoPanel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel productIcon;
    private javax.swing.JLabel productTitleLabel;
    private javax.swing.JSpinner spinner;
    private javax.swing.JLabel unitLabel;
    // End of variables declaration//GEN-END:variables
}
