/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imatapp_g8;

import java.util.ArrayList;
import java.util.List;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;

/**
 *
 * @author rasmusdavidsson
 */
public class FavoriterPanel extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
    private List<Product> favoproducts;

    /**
     * Creates new customizer FavoriterPanel
     */
    public FavoriterPanel() {
        initComponents();
        Controller.db = IMatDataHandler.getInstance();
        favoproducts = Controller.db.favorites();
        fillGrid(favoproducts);
        
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }
    
     public void fillGrid(List<Product> items) {
        for (int i = 0; i < items.size(); i++) {
            if (items.get(i) != null) {
                progrid.add(new ShopItem(items.get(i)));
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progrid = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(930, 630));
        setMinimumSize(new java.awt.Dimension(930, 630));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(930, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progrid.setBackground(new java.awt.Color(255, 255, 255));
        progrid.setAlignmentX(0.0F);
        progrid.setAlignmentY(0.0F);
        progrid.setAutoscrolls(true);
        progrid.setOpaque(false);
        progrid.setLayout(new java.awt.GridLayout());
        add(progrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 930, 520));

        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Favoriter");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 100, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel progrid;
    // End of variables declaration//GEN-END:variables
}
