/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imatapp_g8;

import java.awt.Color;

/**
 *
 * @author rasmusdavidsson
 */
public class LoginPopup extends javax.swing.JPanel {
    
    Controller controller;

    /**
     * Creates new customizer LoginPopup
     */
    public LoginPopup() {
        initComponents();
        controller = Controller.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passWtxt = new javax.swing.JTextField();
        usernameTxt = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        forgottenPwdBtn = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(350, 300));
        setMinimumSize(new java.awt.Dimension(350, 300));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(350, 300));
        setLayout(null);

        passWtxt.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        passWtxt.setForeground(new java.awt.Color(153, 153, 153));
        passWtxt.setText("Lösenord..");
        passWtxt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8)));
        passWtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passWtxtFocusLost(evt);
            }
        });
        passWtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passWtxtMouseClicked(evt);
            }
        });
        add(passWtxt);
        passWtxt.setBounds(20, 90, 249, 40);

        usernameTxt.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        usernameTxt.setForeground(new java.awt.Color(153, 153, 153));
        usernameTxt.setText("Användarnamn..");
        usernameTxt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8)));
        usernameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTxtFocusLost(evt);
            }
        });
        usernameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameTxtMouseClicked(evt);
            }
        });
        add(usernameTxt);
        usernameTxt.setBounds(20, 40, 249, 40);

        loginBtn.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red2_icon.png"))); // NOI18N
        loginBtn.setText("Logga in");
        loginBtn.setAlignmentY(0.0F);
        loginBtn.setBorder(null);
        loginBtn.setContentAreaFilled(false);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        loginBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginBtn.setIconTextGap(0);
        loginBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        loginBtn.setMaximumSize(new java.awt.Dimension(250, 46));
        loginBtn.setMinimumSize(new java.awt.Dimension(250, 46));
        loginBtn.setPreferredSize(new java.awt.Dimension(250, 46));
        loginBtn.setRequestFocusEnabled(false);
        loginBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/red2_icon_rollover.png"))); // NOI18N
        loginBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/red2_icon_selected.png"))); // NOI18N
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        add(loginBtn);
        loginBtn.setBounds(20, 140, 249, 40);

        registerBtn.setText("Registrera");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        add(registerBtn);
        registerBtn.setBounds(20, 195, 120, 30);

        forgottenPwdBtn.setText("Glömt lösenord");
        add(forgottenPwdBtn);
        forgottenPwdBtn.setBounds(148, 195, 120, 30);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/popup.png"))); // NOI18N
        add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 287, 250);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameTxtMouseClicked
        //trycker på användarnamn txt:t
        if(usernameTxt.getText().equals("Användarnamn..")){
            usernameTxt.setText("");
            usernameTxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_usernameTxtMouseClicked

    private void passWtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passWtxtMouseClicked
        //trycker på password txt:t
        if(passWtxt.getText().equals("Lösenord..")){
            passWtxt.setText("");
            passWtxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_passWtxtMouseClicked

    private void usernameTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTxtFocusLost
        // förlorar focus på användarnamn
        if(usernameTxt.getText().equals("")){
           usernameTxt.setForeground(Color.lightGray);
           usernameTxt.setText("Användarnamn..");
        }
    }//GEN-LAST:event_usernameTxtFocusLost

    private void passWtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passWtxtFocusLost
        // förlorar focus på lösenord
        if(passWtxt.getText().equals("")){
            passWtxt.setForeground(Color.lightGray);
            passWtxt.setText("Lösenord..");
        }
        
    }//GEN-LAST:event_passWtxtFocusLost

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed

    }//GEN-LAST:event_loginBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        controller.showRegister();
    }//GEN-LAST:event_registerBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton forgottenPwdBtn;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField passWtxt;
    private javax.swing.JButton registerBtn;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
