/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imatapp_g8;

/**
 *
 * @author rasmusdavidsson
 */
import se.chalmers.ait.dat215.project.*;
public class MyPagePanel extends javax.swing.JPanel {
    
    Controller controller;
    Customer customer;
    User user;
    /**
     * Creates new customizer MyPagePanel
     */
    public MyPagePanel() {
        initComponents();
        controller = Controller.getInstance();
        Controller.db = IMatDataHandler.getInstance();
        customer = Controller.db.getCustomer();
        user = Controller.db.getUser();
        myPagenameLabel.setText(customer.getFirstName());
        myPageaddressLabel.setText(customer.getAddress());
        myPagemailLabel.setText(customer.getEmail());
        myPagelastnameLabel.setText(customer.getLastName());
        myPagemobileLabel.setText(customer.getMobilePhoneNumber());
        myPagephoneLabel.setText(customer.getPhoneNumber());
        myPageortLabel.setText(customer.getPostAddress());
        myPagepostalcodeLabel.setText(customer.getPostCode());
        myPageusernameLabel.setText(user.getUserName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        myPagenameLabel = new javax.swing.JLabel();
        myPagelastnameLabel = new javax.swing.JLabel();
        myPageaddressLabel = new javax.swing.JLabel();
        myPagemailLabel = new javax.swing.JLabel();
        myPagemobileLabel = new javax.swing.JLabel();
        myPagephoneLabel = new javax.swing.JLabel();
        myPageusernameLabel = new javax.swing.JLabel();
        myPageortLabel = new javax.swing.JLabel();
        myPagepostalcodeLabel = new javax.swing.JLabel();
        modifyBtn = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(930, 630));
        setMinimumSize(new java.awt.Dimension(930, 630));
        setPreferredSize(new java.awt.Dimension(930, 630));
        setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Namn:");
        add(jLabel1);
        jLabel1.setBounds(250, 115, 70, 16);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Efternamn:");
        add(jLabel2);
        jLabel2.setBounds(240, 149, 80, 16);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Address:");
        add(jLabel3);
        jLabel3.setBounds(270, 183, 50, 16);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("E-post:");
        add(jLabel4);
        jLabel4.setBounds(120, 217, 200, 16);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Mobil Nummer:");
        add(jLabel5);
        jLabel5.setBounds(120, 251, 200, 16);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Telefon Nummer:");
        add(jLabel6);
        jLabel6.setBounds(120, 285, 200, 16);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Post Kod:");
        add(jLabel7);
        jLabel7.setBounds(120, 387, 200, 16);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Ort:");
        add(jLabel8);
        jLabel8.setBounds(120, 353, 200, 16);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Användarnamn:");
        add(jLabel9);
        jLabel9.setBounds(120, 319, 200, 16);

        jLabel10.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Mina Uppgifter");
        add(jLabel10);
        jLabel10.setBounds(387, 18, 154, 25);
        add(jSeparator1);
        jSeparator1.setBounds(222, 49, 486, 12);
        add(myPagenameLabel);
        myPagenameLabel.setBounds(330, 115, 200, 20);
        add(myPagelastnameLabel);
        myPagelastnameLabel.setBounds(330, 149, 200, 20);
        add(myPageaddressLabel);
        myPageaddressLabel.setBounds(330, 183, 200, 20);
        add(myPagemailLabel);
        myPagemailLabel.setBounds(330, 217, 200, 20);
        add(myPagemobileLabel);
        myPagemobileLabel.setBounds(330, 251, 200, 20);
        add(myPagephoneLabel);
        myPagephoneLabel.setBounds(330, 285, 200, 20);
        add(myPageusernameLabel);
        myPageusernameLabel.setBounds(330, 319, 200, 20);
        add(myPageortLabel);
        myPageortLabel.setBounds(330, 353, 200, 20);
        add(myPagepostalcodeLabel);
        myPagepostalcodeLabel.setBounds(330, 387, 200, 20);

        modifyBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modifyBtn.setText("Redigera");
        modifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBtnActionPerformed(evt);
            }
        });
        add(modifyBtn);
        modifyBtn.setBounds(800, 573, 110, 40);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(100, 110, 97, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void modifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBtnActionPerformed
        controller.showEditUser();
    }//GEN-LAST:event_modifyBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        controller.showFavoPanel();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton modifyBtn;
    private javax.swing.JLabel myPageaddressLabel;
    private javax.swing.JLabel myPagelastnameLabel;
    private javax.swing.JLabel myPagemailLabel;
    private javax.swing.JLabel myPagemobileLabel;
    private javax.swing.JLabel myPagenameLabel;
    private javax.swing.JLabel myPageortLabel;
    private javax.swing.JLabel myPagephoneLabel;
    private javax.swing.JLabel myPagepostalcodeLabel;
    private javax.swing.JLabel myPageusernameLabel;
    // End of variables declaration//GEN-END:variables
}
