/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imatapp_g8;

import java.awt.Color;
import java.util.Arrays;
import se.chalmers.ait.dat215.project.*;

/**
 *
 * @author rasmusdavidsson
 */
public class Register extends javax.swing.JPanel {
    
    Controller controller;
    Customer customer;
    User user;
    boolean isLoggedIn;
    /**
     * Creates new customizer Register
     */
    public Register() {
        initComponents();
        controller = Controller.getInstance();
        errorLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerTxtLabel = new javax.swing.JLabel();
        regNameLabel = new javax.swing.JLabel();
        regLastNameLabel = new javax.swing.JLabel();
        regEmailLabel = new javax.swing.JLabel();
        regUsernameLabel = new javax.swing.JLabel();
        regPassWLabel = new javax.swing.JLabel();
        regAddressLabel = new javax.swing.JLabel();
        regVerifyPWLabel = new javax.swing.JLabel();
        regPostalCodeLabel = new javax.swing.JLabel();
        regOrtLabel = new javax.swing.JLabel();
        regMobilePhoneNbr = new javax.swing.JLabel();
        regPhoneNbr = new javax.swing.JLabel();
        regPwField = new javax.swing.JPasswordField();
        regVerifyPwField = new javax.swing.JPasswordField();
        regUsernameField = new javax.swing.JTextField();
        regEmailField = new javax.swing.JTextField();
        regNameField = new javax.swing.JTextField();
        regLastNameField = new javax.swing.JTextField();
        regPostalCodeField = new javax.swing.JTextField();
        regPhoneNbrField = new javax.swing.JTextField();
        regAddressField = new javax.swing.JTextField();
        regMobileNbrField = new javax.swing.JTextField();
        regOrtField = new javax.swing.JTextField();
        regSeparator = new javax.swing.JSeparator();
        registerBtn = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(930, 2147483647));
        setMinimumSize(new java.awt.Dimension(930, 630));
        setPreferredSize(new java.awt.Dimension(930, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerTxtLabel.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        registerTxtLabel.setForeground(new java.awt.Color(255, 102, 102));
        registerTxtLabel.setText("Registrering");
        add(registerTxtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        regNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regNameLabel.setText("Namn: *");
        regNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(regNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 80, -1));

        regLastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regLastNameLabel.setText("Efternamn: *");
        add(regLastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 110, -1));

        regEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regEmailLabel.setText("E-post: *");
        regEmailLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(regEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 80, -1));

        regUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regUsernameLabel.setText("Användarnamn: *");
        add(regUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 110, -1));

        regPassWLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regPassWLabel.setText("Lösenord: *");
        regPassWLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(regPassWLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 80, -1));

        regAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regAddressLabel.setText("Address: *");
        regAddressLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(regAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 80, -1));

        regVerifyPWLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regVerifyPWLabel.setText("Bekräfta Lösenord: *");
        add(regVerifyPWLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 140, -1));

        regPostalCodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regPostalCodeLabel.setText("Post kod: *");
        add(regPostalCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 110, -1));

        regOrtLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regOrtLabel.setText("Ort:");
        regOrtLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(regOrtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 80, -1));

        regMobilePhoneNbr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regMobilePhoneNbr.setText("Mobil Nummer:");
        regMobilePhoneNbr.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(regMobilePhoneNbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 110, -1));

        regPhoneNbr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        regPhoneNbr.setText("Telefon Nummer:");
        regPhoneNbr.setToolTipText("");
        add(regPhoneNbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 110, -1));
        add(regPwField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 180, -1));
        add(regVerifyPwField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 180, -1));
        add(regUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 180, -1));
        add(regEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 180, -1));
        add(regNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 180, -1));
        add(regLastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 180, -1));
        add(regPostalCodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 180, -1));
        add(regPhoneNbrField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 180, -1));
        add(regAddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 180, -1));
        add(regMobileNbrField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 180, -1));
        add(regOrtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 180, -1));
        add(regSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 400, 10));

        registerBtn.setFont(new java.awt.Font("Helvetica", 0, 22)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red2_icon.png"))); // NOI18N
        registerBtn.setText("Registrera");
        registerBtn.setAlignmentY(0.0F);
        registerBtn.setContentAreaFilled(false);
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registerBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        registerBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registerBtn.setIconTextGap(0);
        registerBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        registerBtn.setMaximumSize(new java.awt.Dimension(250, 46));
        registerBtn.setMinimumSize(new java.awt.Dimension(250, 46));
        registerBtn.setPreferredSize(new java.awt.Dimension(250, 46));
        registerBtn.setRequestFocusEnabled(false);
        registerBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/red2_icon_rollover.png"))); // NOI18N
        registerBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/red2_icon_selected.png"))); // NOI18N
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 545, 280, 40));

        errorLabel.setForeground(new java.awt.Color(255, 0, 51));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setText("Fyll i där det är rödmarkerat");
        add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 495, 280, 32));
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        //trycker på registrera knappen..
        if (checkRequiredFields()){
            Controller.db.reset();
            errorLabel.setVisible(false);
            customer = Controller.db.getCustomer();
            user = Controller.db.getUser();
            customer.setAddress(regAddressField.getText());
            customer.setEmail(regEmailField.getText());
            customer.setFirstName(regNameField.getText());
            customer.setLastName(regLastNameField.getText());
            customer.setMobilePhoneNumber(regMobileNbrField.getText());
            customer.setPhoneNumber(regPhoneNbrField.getText());
            customer.setPostAddress(regOrtField.getText());
            customer.setPostCode(regPostalCodeField.getText());
            user.setPassword(String.valueOf(regPwField.getPassword()));
            user.setUserName(regUsernameField.getText());
            controller.showFeatured();
            controller.toggleLoginOrNameBtn(true);
            
            
            
            //set pw, addres osv.. allt
            //set if logged in osv...

            //Sida där du har lyckats att registrera dig(till mina sidor)
        } else {
            errorLabel.setVisible(true);
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private boolean checkRequiredFields(){
        checkName();
        checkLastName();
        checkEmail();
        checkUserName();
        checkPasswordnVerify();
        checkAddress();
        checkPostalCode();
        boolean ifTrue = checkName() && checkLastName()&&checkEmail()&&checkUserName()&&checkPasswordnVerify()&&checkAddress()&&checkPostalCode();
        return ifTrue;
    }
    
    private boolean checkName(){
        if (regNameField.getText().equals("")){
            regNameLabel.setForeground(Color.red);
            return false;
        }
        regNameLabel.setForeground(Color.black);
        return true;
    }
    
    private boolean checkLastName(){
        if (regLastNameField.getText().equals("")){
            regLastNameLabel.setForeground(Color.red);
            return false;
        }
        regLastNameLabel.setForeground(Color.black);
        return true;
    }
    
    private boolean checkEmail(){
        if (regEmailField.getText().equals("")){
            regEmailLabel.setForeground(Color.red);
            return false;
        }
        regEmailLabel.setForeground(Color.black);
        return true;
    }
    
    private boolean checkUserName(){
        if (regUsernameField.getText().equals("")){
            regUsernameLabel.setForeground(Color.red);
            return false;
        }
        regUsernameLabel.setForeground(Color.black);
        return true;
    }

    private boolean checkPasswordnVerify(){ 
        char [] input = regPwField.getPassword();
        if (!isPasswordCorrect(input) || input.length < 2){
            
                regPassWLabel.setForeground(Color.red);
                regVerifyPWLabel.setForeground(Color.red);
                return false;
        } 
        regPassWLabel.setForeground(Color.black);
        regVerifyPWLabel.setForeground(Color.black);
        return true;
    }
    
    private boolean isPasswordCorrect(char[] input){
        boolean isCorrect = true;
        char [] correctPassword = regVerifyPwField.getPassword();
        if(input.length != correctPassword.length){
            isCorrect = false;
        } else {
            isCorrect = Arrays.equals(input,correctPassword);
        }
        return isCorrect;
    } 
        
    private boolean checkAddress(){
        if (regAddressField.getText().equals("")){
            regAddressLabel.setForeground(Color.red);
            return false;
        }
        regAddressLabel.setForeground(Color.black);
        return true;
    }
    
    private boolean checkPostalCode(){
        if (regPostalCodeField.getText().equals("")){
            regPostalCodeLabel.setForeground(Color.red);
            return false;
        }
        regPostalCodeLabel.setForeground(Color.black);
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField regAddressField;
    private javax.swing.JLabel regAddressLabel;
    private javax.swing.JTextField regEmailField;
    private javax.swing.JLabel regEmailLabel;
    private javax.swing.JTextField regLastNameField;
    private javax.swing.JLabel regLastNameLabel;
    private javax.swing.JTextField regMobileNbrField;
    private javax.swing.JLabel regMobilePhoneNbr;
    private javax.swing.JTextField regNameField;
    private javax.swing.JLabel regNameLabel;
    private javax.swing.JTextField regOrtField;
    private javax.swing.JLabel regOrtLabel;
    private javax.swing.JLabel regPassWLabel;
    private javax.swing.JLabel regPhoneNbr;
    private javax.swing.JTextField regPhoneNbrField;
    private javax.swing.JTextField regPostalCodeField;
    private javax.swing.JLabel regPostalCodeLabel;
    private javax.swing.JPasswordField regPwField;
    private javax.swing.JSeparator regSeparator;
    private javax.swing.JTextField regUsernameField;
    private javax.swing.JLabel regUsernameLabel;
    private javax.swing.JLabel regVerifyPWLabel;
    private javax.swing.JPasswordField regVerifyPwField;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel registerTxtLabel;
    // End of variables declaration//GEN-END:variables
}