/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imatapp_g8;

import java.awt.Color;

/**
 *
 * @author rasmusdavidsson
 */
public class Register extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer Register
     */
    public Register() {
        initComponents();
        errorLabel.setVisible(false);
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerTxtLabel = new javax.swing.JLabel();
        regNameLabel = new javax.swing.JLabel();
        regLastNameLabel = new javax.swing.JLabel();
        regEmailLabel = new javax.swing.JLabel();
        regUsernameLabel = new javax.swing.JLabel();
        regPassWLabel = new javax.swing.JLabel();
        regAddressLabel = new javax.swing.JLabel();
        regVerifyPWLabel = new javax.swing.JLabel();
        regPostalCodeLabel = new javax.swing.JLabel();
        regOrtLabel = new javax.swing.JLabel();
        regMobilePhoneNbr = new javax.swing.JLabel();
        regPhoneNbr = new javax.swing.JLabel();
        regPwField = new javax.swing.JPasswordField();
        regVerifyPwField = new javax.swing.JPasswordField();
        regUsernameField = new javax.swing.JTextField();
        regEmailField = new javax.swing.JTextField();
        regNameField = new javax.swing.JTextField();
        regLastNameField = new javax.swing.JTextField();
        regPostalCodeField = new javax.swing.JTextField();
        regPhoneNbrField = new javax.swing.JTextField();
        regAddressField = new javax.swing.JTextField();
        regMobileNbrField = new javax.swing.JTextField();
        regOrtField = new javax.swing.JTextField();
        regSeparator = new javax.swing.JSeparator();
        registerBtn = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        registerTxtLabel.setFont(new java.awt.Font("Helvetica", 0, 36)); // NOI18N
        registerTxtLabel.setForeground(new java.awt.Color(255, 102, 102));
        registerTxtLabel.setText("Registrering");

        regNameLabel.setText("Namn: *");

        regLastNameLabel.setText("Efternamn: *");

        regEmailLabel.setText("E-mail: *");

        regUsernameLabel.setText("Användarnamn: *");

        regPassWLabel.setText("Lösenord: *");

        regAddressLabel.setText("Address: *");

        regVerifyPWLabel.setText("Bekräfta Lösenord: *");

        regPostalCodeLabel.setText("Post kod: *");

        regOrtLabel.setText("Ort:");

        regMobilePhoneNbr.setText("Mobil Nummer:");

        regPhoneNbr.setText("Telefon Nummer:");
        regPhoneNbr.setToolTipText("");

        registerBtn.setFont(new java.awt.Font("Helvetica", 0, 22)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red2_icon.png"))); // NOI18N
        registerBtn.setText("Registrera");
        registerBtn.setAlignmentY(0.0F);
        registerBtn.setContentAreaFilled(false);
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registerBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        registerBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registerBtn.setIconTextGap(0);
        registerBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        registerBtn.setMaximumSize(new java.awt.Dimension(250, 46));
        registerBtn.setMinimumSize(new java.awt.Dimension(250, 46));
        registerBtn.setPreferredSize(new java.awt.Dimension(250, 46));
        registerBtn.setRequestFocusEnabled(false);
        registerBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/red2_icon_rollover.png"))); // NOI18N
        registerBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/red2_icon_selected.png"))); // NOI18N
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(255, 0, 51));
        errorLabel.setText("Fyll i där det är rödmarkerat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(regSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(registerTxtLabel)
                .addGap(311, 311, 311))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(regNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(regNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(regLastNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(regLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(regEmailLabel)
                        .addGap(18, 18, 18)
                        .addComponent(regEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(regUsernameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(regUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(regPassWLabel)
                        .addGap(18, 18, 18)
                        .addComponent(regPwField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(regVerifyPWLabel)
                        .addGap(18, 18, 18)
                        .addComponent(regVerifyPwField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(regAddressLabel)
                        .addGap(18, 18, 18)
                        .addComponent(regAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(regPostalCodeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(regPostalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(regOrtLabel)
                        .addGap(18, 18, 18)
                        .addComponent(regOrtField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(regMobilePhoneNbr)
                                .addGap(18, 18, 18)
                                .addComponent(regMobileNbrField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(regPhoneNbr)))
                        .addGap(18, 18, 18)
                        .addComponent(regPhoneNbrField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(registerTxtLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regNameLabel)
                            .addComponent(regLastNameLabel))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regEmailLabel)
                            .addComponent(regUsernameLabel))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regPwField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regVerifyPwField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regPassWLabel)
                            .addComponent(regVerifyPWLabel))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regPostalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regAddressLabel)
                            .addComponent(regPostalCodeLabel))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regMobileNbrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regPhoneNbrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regMobilePhoneNbr)
                            .addComponent(regPhoneNbr))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(regOrtLabel))
                    .addComponent(regOrtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        //trycker på registrera knappen..
        if(checkRequiredFields()){
            
            //Sida där du har lyckats att registrera dig(till mina sidor)
        }else{
            errorLabel.setVisible(true);
        }
        
    }//GEN-LAST:event_registerBtnActionPerformed

    private boolean checkRequiredFields(){
        return checkName() && checkLastName()&&checkEmail();
        
        
    }
    
    private boolean checkName(){
        if(regNameField.getText().equals("")){
            regNameLabel.setForeground(Color.red);
            return false;
        }
        return true;
    }
    private boolean checkLastName(){
        if(regLastNameField.getText().equals("")){
            regLastNameLabel.setForeground(Color.red);
            return false;
        }
        return true;
    }
    private boolean checkEmail(){
        if(regEmailField.getText().equals("")){
            regEmailLabel.setForeground(Color.red);
            return false;
        }
        return true;
    }
    private boolean checkUserName(){
    
        if(regUsernameField.getText().equals("")){
            regUsernameLabel.setForeground(Color.red);
            return false;
        }
        return true;
    }
    private boolean checkPasswordnVerify(){ //instabilt!! bör förbättras!
        System.out.println("test1");
        if(regPwField.getPassword().equals("")){
            
                regPassWLabel.setForeground(Color.red);
                System.out.println("test2");
                return false;
        } else if((regPwField.getPassword() == regVerifyPwField.getPassword())){
        
            return true;
        }
        return false;
    }
    private boolean checkAddress(){
        if(regAddressField.getText().equals("")){
            regAddressLabel.setForeground(Color.red);
            return false;
        }
        return true;
    }
    private boolean checkPostalCode(){
        if(regPostalCodeField.getText().equals("")){
            regPostalCodeLabel.setForeground(Color.red);
            return false;
        }
        return true;
    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField regAddressField;
    private javax.swing.JLabel regAddressLabel;
    private javax.swing.JTextField regEmailField;
    private javax.swing.JLabel regEmailLabel;
    private javax.swing.JTextField regLastNameField;
    private javax.swing.JLabel regLastNameLabel;
    private javax.swing.JTextField regMobileNbrField;
    private javax.swing.JLabel regMobilePhoneNbr;
    private javax.swing.JTextField regNameField;
    private javax.swing.JLabel regNameLabel;
    private javax.swing.JTextField regOrtField;
    private javax.swing.JLabel regOrtLabel;
    private javax.swing.JLabel regPassWLabel;
    private javax.swing.JLabel regPhoneNbr;
    private javax.swing.JTextField regPhoneNbrField;
    private javax.swing.JTextField regPostalCodeField;
    private javax.swing.JLabel regPostalCodeLabel;
    private javax.swing.JPasswordField regPwField;
    private javax.swing.JSeparator regSeparator;
    private javax.swing.JTextField regUsernameField;
    private javax.swing.JLabel regUsernameLabel;
    private javax.swing.JLabel regVerifyPWLabel;
    private javax.swing.JPasswordField regVerifyPwField;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel registerTxtLabel;
    // End of variables declaration//GEN-END:variables
}
