/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imatapp_g8;

import java.util.ArrayList;
import java.util.List;
import se.chalmers.ait.dat215.project.*;

/**
 *
 * @author frellAn
 */
public class ShopPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShopPanel
     */
    public ShopPanel() {
        initComponents();
    }
    
    public ShopPanel(int all) {
        initComponents();
        fillGrid(Controller.db.getProducts());
    }
    
    public ShopPanel(ProductCategory category) {
        initComponents();
        fillGrid(Controller.db.getProducts(category));
    }
    
    public ShopPanel(String search) {
        List<Product> all = new ArrayList<>();
        all = Controller.db.getProducts();
        List<Product> result = new ArrayList<>();
        for (int i = 1; i < all.size(); i++) {
            if (all.get(i).getName().equals(search)) {
                System.out.println("Found you!");
                result.add(all.get(i));
            }
        }
        initComponents();
        fillGrid(result);
    }
    
    public void fillGrid(List<Product> items) {
        for (int i = 1; i < items.size(); i++) {
            productGrid.add(new ShopItem(items.get(i)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productGridScrollPane = new javax.swing.JScrollPane();
        productGrid = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(930, 32767));
        setMinimumSize(new java.awt.Dimension(930, 630));
        setPreferredSize(new java.awt.Dimension(930, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productGridScrollPane.setBorder(null);
        productGridScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        productGridScrollPane.setMaximumSize(new java.awt.Dimension(920, 590));
        productGridScrollPane.setMinimumSize(new java.awt.Dimension(920, 5));

        productGrid.setBackground(new java.awt.Color(255, 255, 255));
        productGrid.setAlignmentX(0.0F);
        productGrid.setAlignmentY(0.0F);
        productGrid.setMaximumSize(new java.awt.Dimension(920, 590));
        productGrid.setLayout(new java.awt.GridLayout(0, 5));
        productGridScrollPane.setViewportView(productGrid);

        add(productGridScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, 920, 581));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel productGrid;
    private javax.swing.JScrollPane productGridScrollPane;
    // End of variables declaration//GEN-END:variables
}
