/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imatapp_g8;

import se.chalmers.ait.dat215.project.*;


/**
 *
 * @author Michel
 */
public class ShoppingCartItem extends javax.swing.JPanel {

    /**
     * Creates new form ShoppingCartItem
     */
    public ShoppingCartItem() {
        initComponents();
    }
    
    public ShoppingCartItem(Product prod) {
        initComponents();
        jLabel1.setIcon(MainWindow.db.getImageIcon(prod, 300, 225));
        jLabel2.setText("" + prod.getPrice());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(276, 276));
        setMinimumSize(new java.awt.Dimension(276, 276));
        setPreferredSize(new java.awt.Dimension(276, 276));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(java.awt.Color.orange);
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        jButton1.setText("Ta Bort");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<Pris>");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
