/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imatapp_g8;

import javax.swing.*;
import se.chalmers.ait.dat215.project.*;

/**
 *
 * @author frellAn
 */
public class TempCartItem extends javax.swing.JPanel {
    
    // Lagt till av Michel
    Controller tempController = Controller.getInstance();
    private Product prod;
    
    
    // Custom variable declaration
    private ImageIcon icon;
    private String name;
    private double price;
    private String unit;

    /**
     * Creates new form ShopItem
     */
    public TempCartItem() {
        initComponents();
    }
    
    public TempCartItem(Product item) {
        icon = MainWindow.db.getImageIcon(item,174,132);
        name = item.getName();
        price = item.getPrice();
        unit = item.getUnit();
        initComponents();
        
        // Lagt till av Michel
        prod = item;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        totalPriceLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        amountLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        priceLabel2 = new javax.swing.JLabel();
        amountPanel = new javax.swing.JPanel();
        itemPrice6 = new javax.swing.JLabel();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(650, 80));
        setMinimumSize(new java.awt.Dimension(650, 80));
        setPreferredSize(new java.awt.Dimension(650, 80));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconLabel.setIcon(icon);
        iconLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        iconLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconLabelMouseClicked(evt);
            }
        });
        add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 60));

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalPriceLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        totalPriceLabel2.setText("40.0 kr");
        totalPriceLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        totalPriceLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalPriceLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(totalPriceLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 10));

        amountLabel.setFont(new java.awt.Font("Myriad Pro Light", 1, 12)); // NOI18N
        amountLabel.setText("Antal");
        jPanel1.add(amountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        priceLabel.setFont(new java.awt.Font("Myriad Pro Light", 1, 12)); // NOI18N
        priceLabel.setText("Pris");
        jPanel1.add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        totalPriceLabel.setFont(new java.awt.Font("Myriad Pro Light", 1, 12)); // NOI18N
        totalPriceLabel.setText("Totalt");
        jPanel1.add(totalPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        priceLabel2.setFont(new java.awt.Font("Myriad Pro Light", 0, 12)); // NOI18N
        priceLabel2.setText("20.0 kr/förp.");
        jPanel1.add(priceLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        amountPanel.setBackground(java.awt.Color.white);
        amountPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemPrice6.setFont(new java.awt.Font("Myriad Pro Light", 0, 12)); // NOI18N
        itemPrice6.setText("2");
        amountPanel.add(itemPrice6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        plusButton.setText("+");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });
        amountPanel.add(plusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 20));

        minusButton.setText("-");
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });
        amountPanel.add(minusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        jPanel1.add(amountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 330, 60));

        nameLabel.setFont(new java.awt.Font("Myriad Pro Light", 1, 18)); // NOI18N
        nameLabel.setText("Mjölk");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jButton1.setText("Ta Bort");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void iconLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconLabelMouseClicked
        tempController.showDetailedView(prod);
    }//GEN-LAST:event_iconLabelMouseClicked

    private void totalPriceLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalPriceLabel2MouseClicked
        tempController.showDetailedView(prod);
    }//GEN-LAST:event_totalPriceLabel2MouseClicked

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minusButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plusButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JPanel amountPanel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel itemPrice6;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton minusButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton plusButton;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceLabel2;
    private javax.swing.JLabel totalPriceLabel;
    private javax.swing.JLabel totalPriceLabel2;
    // End of variables declaration//GEN-END:variables
}
